config/routes.rb
CALM::Application.routes.draw do
  
  # This would do the trick, but definitely not a good approach...
  get 'events', to: 'announcements#index'
  post 'events/new', to: 'events#create'
  put 'events/:id/edit', to: 'events#update'
  
  get 'events/:event_id/signup', to: 'events_signup#new', as: 'events_signup'
  post 'events/:event_id/signup', to: 'events_signup#create'

  resources :research_interests
 
  get '/user/:id', to: 'users#edit', as: 'edit_user'
  patch '/user/:id', to: 'users#update'

  get 'signup', to: 'signup#new'
  post 'signup', to: 'signup#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  post 'logout', to: 'sessions#destroy'
  
  resources :events
  
  resources :announcements
  resources :events
  # map '/' to be a redirect to '/announcements'
  root :to => redirect('/announcements')
  
end

app/models/announcement.rb
class Announcement < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :user_events
    has_many :events, through: :user_events
    has_and_belongs_to_many :research_interests
    # adds virtual attributes for authenticatiosn
    has_secure_password
    
    # validation
    validates :account_name, presence: true, uniqueness: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :current_user
  
  def show
    id = params[:id] # retrieve announcement ID from URI route
    @announcement = Announcement.find(id) # look up announcement by unique ID
    # will render app/views/announcements/show.<extension> by default
  end

  def index
    sort = params[:sort] || session[:sort]
    case sort
    when 'title'
      ordering,@title_header = {:title => :asc}, 'bg-warning hilite'
    when 'release_date'
      ordering,@date_header = {:release_date => :asc}, 'bg-warning hilite'
    end


    @announcements = Announcement.all
    
    if @current_user
      @user_event_ids = UserEvent.where(:user_id => @current_user.id).all.pluck(:event_id)
    end
    
    
    # Hmm... tbh, this event stuff shouldn't be here lol
    e_sort = params[:e_sort] || session[:e_sort]
    case e_sort
    when 'name'
      ordering, @e_name_header = {:name => :asc}, 'bg-light'
    when 'location'
      ordering, @e_location_header = {:location => :asc}, 'bg-light'
    when 'start_at'
      ordering, @e_start_date_header = {:start_at => :asc}, 'bg-light'
    end
    
    if params[:e_sort] != session[:e_sort]
      session[:e_sort] = e_sort
      redirect_to :e_sort => e_sort and return
    end
    @events = Event.all.order(ordering);
    # events.save!
  end 
    
  def new
    # default: render 'new' template
  end

  def create
    @announcement = Announcement.create!(announcement_params) # combines new and save
    flash[:notice] = "#{@announcement.title} was successfully created."
    redirect_to announcements_path
  end

  def edit
    @announcement = Announcement.find params[:id]
   
  end

  def update
    @announcement = Announcement.find params[:id]
    @announcement.update_attributes!(announcement_params)
    flash[:notice] = "#{@announcement.title} was successfully updated."
    redirect_to announcements_path(@announcement)
  end

  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy
    flash[:notice] = "Announcement '#{@announcement.title}' deleted."
    redirect_to announcements_path
  end

  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def announcement_params
    params.require(:announcement).permit(:title, :author, :description, :release_date)
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/announcements/edit.html.erb
<h2>Edit Existing Announcement</h2>
<%= form_tag announcement_path(@announcement), :method => :put do %>
  <%= label :announcement, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :announcement, 'title', :class => 'form-control' %>
  
  <%= label :announcement, :author, 'Author', :class => 'col-form-label' %>
  <%= text_field :announcement, 'author', :class => 'form-control' %>

  <%= label :announcement, :description, 'Content', :class => 'col-form-label' %>
  <%= text_field :announcement, :description, :class => 'form-control' %>
  
  <%= label :announcement, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :announcement, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <p></p>
  
  <%= submit_tag 'Update Announcement Info', :class => 'btn btn-primary' %>
  <%= link_to 'Delete', announcement_path(@announcement), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <%= link_to 'Cancel', announcements_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/announcements/index.html.erb
<!--  This file is app/views/announcements/index.html.erb -->
<p>
  <%= flash[:alert] if flash[:alert] %>
  <%= link_to 'Home', root_path %>
</p>


<% if @current_user %>

<p align="right">
<%= @current_user.email %>
<%= link_to "Log out", logout_path, method: "post", :class => 'btn btn-primary pull-right' %>
<%= link_to "My account", edit_user_url(@current_user), :class => 'btn btn-primary pull-right' %>
</p>
  
<% else %>

<p align="right">
  <%= link_to 'Login', login_path, :class => 'btn btn-primary pull-right ' %>
  <%= link_to 'Signup', signup_url, :class => 'btn btn-primary pull-right' %>
</p>


<% end %>




<h2>Announcements</h2>

<%= form_tag announcements_path, :method => :get do %>
  <%= hidden_field_tag "title_sort", true if @title_header %>
  <%= hidden_field_tag ":release_date_sort", true if @date_header %>
<% end %>

<table class="table table-striped col-md-12" style="width: 100%; table-layout: fixed;" id="announcements">
  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td class="text-nowrap" style="width: 70%;">
          <div class="font-weight-bold">
            <p>
              <%= link_to "#{announcement.title}", announcement_path(announcement) %>
            </p>
          </div>
          <p class="text-truncate">
            <%= announcement.description %>
          </p>
        </td>
        <td class="text-nowrap" style="width: 20%;">
          <div class="font-weight-bold">
            <p>Posted on:</p>
          </div>
          <div>
            <%= announcement.release_date %>
          </div>
        </td>
        
        <td class="text-nowrap" style="width: 10%;">
          <% if is_organizer %>
          <div class="text-center">
            <%= link_to 'Edit', edit_announcement_path(announcement), :class => 'btn btn-primary' %>
          </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if is_organizer %>
<div class="col-md-12 text-center">
  <%= link_to 'Add Announcement', new_announcement_path, :class => 'btn btn-primary' %>
</div>
<% end %>

<p></p>



<!-- Event Table (temp) -->
<h2>Events</h2>

<%= form_tag events_path, :method => :get do %>
  <%= hidden_field_tag ":name_sort", true if @e_name_header %>
  <%= hidden_field_tag ":location_sort", true if @e_location_header %>
  <%= hidden_field_tag ":start_date_sort", true if @e_start_date_header %>
<% end %>

<table class="table table-striped col-md-12" id="events">
  <thead>
    <tr>
      <th class="<%= @e_name_header %>">
        <%= link_to 'Conference', events_path(:e_sort => 'name'), :id => 'e_name_header' %>
      </th>
      <th class="<%= @e_location_header %>">
        <%= link_to 'Location', events_path(:e_sort => 'location'), :id => 'e_location_header' %>
      </th>
      <th class="<%= @e_start_date_header %>">
        <%= link_to 'Starting Date', events_path(:e_sort => 'start_at'), :id => 'e_start_date_header' %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td>
          <%= event.name %>
        </td>
        <td>
          <%= event.location %>
        </td>
        <td>
          <%= event.start_at %>
        </td>
        <td>
          <% if is_organizer %>
          <div class="text-center">
            <%= link_to 'Edit', edit_event_path(event), :class => 'btn btn-outline-primary' %>
          </div>
          <% elsif current_user %>
          <div class="text-center">
            <% if @user_event_ids.include? event.id %>
              <button type="button" class="btn btn-secondary" disabled>Joined</button>
            <% else %>
              <%= link_to 'Join', events_signup_path(event), :class => 'btn btn-outline-primary' %>
            <% end %>
          </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if is_organizer %>
<div class="col-md-12 text-center">
  <%= link_to 'Add Event', new_event_path, :class => 'btn btn-primary' %>
</div>
<% end %>


<% if @current_user %>
<h2>Can see this if logged in</h2>
  <%= text_field :announcement, :title, :class => 'form-control' %>
<% end %>

app/views/announcements/new.html.erb
<h2>Post an Announcement</h2>

<%= form_tag announcements_path, :class => 'form' do %>
  <%= label :announcement, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :announcement, :title, :class => 'form-control' %>
  
  <%= label :announcement, :author, 'Author', :class => 'col-form-label' %>
  <%= text_field :announcement, 'author', :class => 'form-control' %>
  
  <%= label :announcement, :description, 'Content', :class => 'col-form-label' %>
  <%= text_field :announcement, :description, :class => 'form-control' %>
  
  <%= label :announcement, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :announcement, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', announcements_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/announcements/show.html.erb
<!--  app/views/announcements/show.html.erb -->
<h2>Details about <em><%= @announcement.title %></em></h2>

<ul id="details">
  <li>
    Author:
    <%= @announcement.author %>
  </li>
  <li>
    Released on:
    <%= @announcement.release_date.strftime("%B %d, %Y") %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @announcement.description %>
</p>

<div class="row">
  
  <!-- TBD (should check if user is organizer) -->
  <% if current_user %>
  <%= link_to 'Edit', edit_announcement_path(@announcement), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Delete', announcement_path(@announcement), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <% end %>
  
  <%= link_to 'Back to announcement list', announcements_path, :class => 'btn btn-primary col-2' %>
</div>