config/routes.rb
CALM::Application.routes.draw do
  
  # This would do the trick, but definitely not a good approach...
  get 'events', to: 'announcements#index'
  post 'events/new', to: 'events#create'
  put 'events/:id/edit', to: 'events#update'
  
  get 'events/:event_id/signup', to: 'events_signup#new', as: 'events_signup'
  post 'events/:event_id/signup', to: 'events_signup#create'

  resources :research_interests
 
  get '/user/:id', to: 'users#edit', as: 'edit_user'
  patch '/user/:id', to: 'users#update'

  get 'signup', to: 'signup#new'
  post 'signup', to: 'signup#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  post 'logout', to: 'sessions#destroy'
  
  resources :events
  
  resources :announcements
  resources :events
  # map '/' to be a redirect to '/announcements'
  root :to => redirect('/announcements')
  
end

app/models/event.rb
class Event < ActiveRecord::Base
    has_many :user_events
    has_many :users, through: :user_events
    
    def self.to_csv
    attributes = %w{id email name}

    CSV.generate(headers: true) do |csv|
      csv << attributes

      all.each do |user|
        csv << attributes.map{ |attr| user.send(attr) }
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def show
    id = params[:id] # retrieve Event ID from URI route
    @event = Event.find(id) # look up Event by unique ID
    # will render app/views/events/show.<extension> by default
  end

  def index
    # sort = params[:sort] || session[:sort]
    # case sort
    # when 'title'
    #   ordering,@title_header = {:title => :asc}, 'bg-warning hilite'
    # when 'release_date'
    #   ordering,@date_header = {:release_date => :asc}, 'bg-warning hilite'
    # end

    # @events = Event.order(ordering)
  end 
    
  def new
    # default: render 'new' template
  end

  def create
    @event = Event.create!(event_params) # combines new and save
    flash[:notice] = "#{@event.name} (#{@event.location}) was successfully created."
    redirect_to events_path
  end

  def edit
    @event = Event.find params[:id]
    @name = UserEvent.where("event_id = ?", params[:id]).to_a
    @x = @name.map{|x| x.user_id}
    @people = User.where(id: @x).to_a
    
    
  end

  def update
    @event = Event.find params[:id]
    @event.update_attributes!(event_params)
    flash[:notice] = "#{@event.name} was successfully updated."
    redirect_to edit_event_path(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    flash[:notice] = "Event '#{@event.name}' deleted."
    redirect_to events_path
  end

  private
  # Making "internal" methods private is not required, but is a common practice.
  # This helps make clear which methods respond to requests, and which ones do not.
  def event_params
    params.require(:event).permit(:name, :location, :start_at)
  end
end

app/views/events/edit.html.erb
<h2>Edit Existing Event</h2>
<%= form_tag edit_event_path(@event), :method => :put do %>
  <%= label :event, :name, 'Name', :class => 'col-form-label' %>
  <%= text_field :event, 'name', :class => 'form-control' %>
  
  <%= label :event, :location, 'Location', :class => 'col-form-label' %>
  <%= text_field :event, 'location', :class => 'form-control' %>

  <%= label :event, :start_at, 'Starting Date', :class => 'col-form-label'  %>
  <%= date_select :event, :start_at, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  
  <br/>
  <h3>Check Sign-Up Info</h3>
  <!% Need MVC for event signup. Display the people that signed up here  %>
  

 <table class="table table-striped col-md-12">
  <thead>
    <tr>
      <th >
        <%= "First Name" %>
      </th>
      <th >
        <%=  "Last Name" %>
      </th>
    </tr>
  </thead>
  <tbody>
    <% @people.each do |person| %>
    <tr>
        <td>
          <%= person.first_name %>
        </td>
        <td>
          <%= person.last_name %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
  
  <%= link_to 'Export', events_path, :class => 'btn btn-success' %>

<!%=one way to export csv if event signup is done%> 
<!%=
require 'csv'
 
file = "#{Rails.root}/public/event.csv"
 
table = Event.all;0 # ";0" stops output.  Change "Event" to any model.
 
CSV.open( file, 'w' ) do |writer|
  writer << table.first.attributes.map { |a,v| a }
  table.each do |s|
    writer << s.attributes.map { |a,v| v }
  end
end
%>
  
  <br/>
  <%= link_to 'Delete', event_path(@event), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <%= submit_tag 'Update Event Info', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', events_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/events/new.html.erb
<h2>Post an Event</h2>

<%= form_tag new_event_path, :class => 'form' do %>
  <%= label :event, :name, 'Conference', :class => 'col-form-label' %>
  <%= text_field :event, :name, :class => 'form-control' %>
  
  <%= label :event, :location, 'Location', :class => 'col-form-label' %>
  <%= text_field :event, :location, :class => 'form-control' %>

  <%= label :event, :start_at, 'Starting Date', :class => 'col-form-label'  %>
  <%= date_select :event, :start_at, {}, :class => 'form-control col-2 d-inline' %>
  
  <p></p>
  
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', events_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/events/show.html.erb
<!--  app/views/events/show.html.erb -->
<h2>Details about <em><%= @event.name %></em></h2>

<ul id="details">
  <li>
    Starting Date:
    <%= @event.start_at.strftime("%B %d, %Y") %>
  </li>
</ul>

<h3>Location:</h3>
<p id="location">
  <%= @event.location %>
</p>

<div class="row">
  
  <!-- TBD (should check if user is organizer) -->
  <% if current_user %>
  <%= link_to 'Edit', edit_event_path(@event), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Delete', event_path(@event), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <% end %>
  
  <%= link_to 'Back to event list', events_path, :class => 'btn btn-primary col-2' %>
</div>