config/routes.rb
CALM::Application.routes.draw do
  
  # This would do the trick, but definitely not a good approach...
  get 'events', to: 'announcements#index'
  post 'events/new', to: 'events#create'
  put 'events/:id/edit', to: 'events#update'
  
  get 'events/:event_id/signup', to: 'events_signup#new', as: 'events_signup'
  post 'events/:event_id/signup', to: 'events_signup#create'

  resources :research_interests
 
  get '/user/:id', to: 'users#edit', as: 'edit_user'
  patch '/user/:id', to: 'users#update'

  get 'signup', to: 'signup#new'
  post 'signup', to: 'signup#create'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  post 'logout', to: 'sessions#destroy'
  
  resources :events
  
  resources :announcements
  resources :events
  # map '/' to be a redirect to '/announcements'
  root :to => redirect('/announcements')
  
end

app/models/research_interest.rb
class ResearchInterest < ActiveRecord::Base
    has_and_belongs_to_many :users
end

app/controllers/research_interests_controller.rb
class ResearchInterestsController < ApplicationController
  before_action :set_research_interest, only: [:show, :edit, :update, :destroy]

  # GET /research_interests
  def index
    @research_interests = ResearchInterest.all
  end

  # GET /research_interests/1
  def show
  end

  # GET /research_interests/new
  def new
    @research_interest = ResearchInterest.new
  end

  # GET /research_interests/1/edit
  def edit
  end

  # POST /research_interests
  def create
    @research_interest = ResearchInterest.new(research_interest_params)

    if @research_interest.save
      redirect_to @research_interest, notice: 'Research interest was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /research_interests/1
  def update
    if @research_interest.update(research_interest_params)
      redirect_to @research_interest, notice: 'Research interest was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /research_interests/1
  def destroy
    @research_interest.destroy
    redirect_to research_interests_url, notice: 'Research interest was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_research_interest
      @research_interest = ResearchInterest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def research_interest_params
      params.require(:research_interest).permit(:field)
    end
end

app/helpers/research_interests_helper.rb
module ResearchInterestsHelper
end

app/views/research_interests/_form.html.erb
<%= form_for(@research_interest) do |f| %>
  <% if @research_interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@research_interest.errors.count, "error") %> prohibited this research_interest from being saved:</h2>

      <ul>
      <% @research_interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :field %><br>
    <%= f.text_field :field %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/research_interests/edit.html.erb
<h1>Editing Research Interest</h1>

<%= render 'form' %>

<%= link_to 'Show', @research_interest %> |
<%= link_to 'Back', research_interests_path %>

app/views/research_interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Research Interests</h1>

<table>
  <thead>
    <tr>
      <th>Field</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @research_interests.each do |research_interest| %>
      <tr>
        <td><%= research_interest.field %></td>
        <td><%= link_to 'Show', research_interest %></td>
        <td><%= link_to 'Edit', edit_research_interest_path(research_interest) %></td>
        <td><%= link_to 'Destroy', research_interest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Research interest', new_research_interest_path %>

app/views/research_interests/new.html.erb
<h1>New Research Interest</h1>

<%= render 'form' %>

<%= link_to 'Back', research_interests_path %>

app/views/research_interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Field:</strong>
  <%= @research_interest.field %>
</p>

<%= link_to 'Edit', edit_research_interest_path(@research_interest) %> |
<%= link_to 'Back', research_interests_path %>